# Generated by Django 5.2.3 on 2025-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField(max_length=10)),
                ('f_name', models.TextField(max_length=20)),
                ('f_description', models.TextField(max_length=200)),
                ('f_price', models.FloatField()),
                ('f_category', models.TextField(max_length=30)),
                ('f_scientific_name', models.CharField(max_length=100)),
            ],
        ),
    ]
