# Generated by Django 5.2.3 on 2025-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flora',
            name='f_id',
        ),
        migrations.AddField(
            model_name='flora',
            name='f_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='f_image',
            field=models.ImageField(blank=True, null=True, upload_to='flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='f_category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flora',
            name='f_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flora',
            name='f_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
