# Generated by Django 5.2.3 on 2025-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0005_supportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
